# Generated by Django 4.1.3 on 2022-11-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turista',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='ciudad_destino',
            field=models.CharField(default='pereira', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='destino',
            field=models.CharField(default='Ukumari', max_length=255),
            preserve_default=False,
        ),
    ]
