# Generated by Django 4.1.3 on 2022-11-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_turista_ciudad_cuestionario_ciudad_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='T_transporte',
            field=models.CharField(choices=[('C', 'carro'), ('M', 'moto'), ('V-A', 'vehiculo alquilado'), ('B', 'bus'), ('T', 'taxi')], max_length=5),
        ),
    ]
