# Generated by Django 4.1.3 on 2022-11-22 08:09

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_cuestionario_t_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='T_transporte',
            field=models.CharField(choices=[('Carro', 'carro'), ('Moto', 'moto'), ('vehiculo alquilado', 'vehiculo alquilado'), ('Bus', 'bus'), ('Taxi', 'taxi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='ciudad_destino',
            field=task.models.CharLower(max_length=255),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='destino',
            field=task.models.CharLower(max_length=255),
        ),
        migrations.AlterField(
            model_name='turista',
            name='nombre',
            field=task.models.CharLower(max_length=255),
        ),
        migrations.AlterField(
            model_name='turista',
            name='pais',
            field=task.models.CharLower(max_length=255),
        ),
    ]
